title: Alya Husna Ibrahim
logo: /assets/img/headshot_circle.png
description: Aspiring Cybersecurity Analyst | Final year IT Student
 <ul>
          <li><a href="https://www.linkedin.com/in/danial-mutalib-387580194/">Follow Me<strong>Linkedin</strong></a></li>
          <li><a href="https://github.com/danialmutalibs">Follow Me<strong>GitHub</strong></a></li>
          <li><a href="mailto:danialmutalib.s@gmail.com">Contact Me<strong>Email</strong></a></li>
</ul>
theme: jekyll-theme-minimal
